<?php

use Illuminate\Database\Seeder;

class TblinstanciaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tblinstancia')->delete();
        
        \DB::table('tblinstancia')->insert(array (
            0 => 
            array (
                'id' => 1,
                'c_instancia' => '000',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070101',
                'x_corto' => '1JC',
                'x_nom_instancia' => 'JUZGADO CONFIGURACION',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'c_instancia' => '001',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3302',
                'c_ubigeo' => '070106',
                'x_corto' => '1SM',
                'x_nom_instancia' => 'SALA MIXTA - SEDE CENTRAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'c_instancia' => '002',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '04',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '1JM',
                'x_nom_instancia' => 'JUZGADO MIXTO - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'c_instancia' => '003',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '04',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '1JMT',
                'x_nom_instancia' => 'JUZGADO MIXTO TRANSITORIO - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'c_instancia' => '004',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '2JP',
                'x_nom_instancia' => '2° JUZGADO PENAL - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'c_instancia' => '005',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '1JIP',
                'x_nom_instancia' => 'JUZGADO DE LA INVESTIGACION PREPARATORIA - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'c_instancia' => '006',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '1JPT',
                'x_nom_instancia' => 'JUZGADO PENAL TRANSITORIO - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'c_instancia' => '007',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '1JTS',
                'x_nom_instancia' => 'JUZGADO DE TRANSITO Y SEGURIDAD VIAL TRANSITORIO -VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'c_instancia' => '008',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3304',
                'c_ubigeo' => '070106',
                'x_corto' => '2JPL',
                'x_nom_instancia' => '2° JUZGADO DE PAZ LETRADO',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'c_instancia' => '009',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '1JP',
                'x_nom_instancia' => '1° JUZGADO PENAL - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'c_instancia' => '010',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '1JPL',
                'x_nom_instancia' => '1° JUZGADO DE PAZ LETRADO - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'c_instancia' => '011',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3308',
                'c_ubigeo' => '070107',
                'x_corto' => 'JPLT',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO TRANSITORIO - MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'c_instancia' => '012',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '1SPA',
                'x_nom_instancia' => 'SALA PENAL DE APELACIONES - SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'c_instancia' => '013',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '1JUP',
                'x_nom_instancia' => '1° JUZGADO PENAL UNIPERSONAL- PROC. FLAGRANCIA - SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'c_instancia' => '014',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '1JC',
                'x_nom_instancia' => 'JUZGADO PENAL COLEGIADO - SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'c_instancia' => '015',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '2JUP',
                'x_nom_instancia' => '2° JUZGADO PENAL UNIPERSONAL - SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'c_instancia' => '016',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '1JIP',
                'x_nom_instancia' => '1° JUZGADO DE INVESTIGACION PREPARAT - PROC.FLAG-SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'c_instancia' => '017',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '2JIP',
                'x_nom_instancia' => '2° JUZGADO DE LA INVESTIGACION PREPATORIA - SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'c_instancia' => '018',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3304',
                'c_ubigeo' => '070106',
                'x_corto' => '1JF',
                'x_nom_instancia' => '1° JUZGADO DE FAMILIA - SEDE ANEXO 1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'c_instancia' => '019',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3304',
                'c_ubigeo' => '070106',
                'x_corto' => '1JTS',
                'x_nom_instancia' => 'JUZGADO DE TRANSITO Y SEGURIDAD VIAL - SEDE ANEXO 1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'c_instancia' => '020',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3304',
                'c_ubigeo' => '070106',
                'x_corto' => '1JC',
                'x_nom_instancia' => '1° JUZGADO CIVIL - SEDE ANEXO 1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'c_instancia' => '021',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '04',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => '1JMT',
                'x_nom_instancia' => 'JUZGADO MIXTO TRANSITORIO - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'c_instancia' => '022',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => '4JPL',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'c_instancia' => '023',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '04',
                'c_sede' => '3308',
                'c_ubigeo' => '070107',
                'x_corto' => '1JMT',
                'x_nom_instancia' => 'JUZGADO MIXTO TRANSITORIO - SEDE MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'c_instancia' => '024',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3306',
                'c_ubigeo' => '070106',
                'x_corto' => '1SP',
                'x_nom_instancia' => 'SALA PENAL - SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'c_instancia' => '025',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '2JC',
                'x_nom_instancia' => '2° JUZGADO CIVIL - SEDE ANEXO 2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'c_instancia' => '026',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '3JC',
                'x_nom_instancia' => '3° JUZGADO CIVIL - SEDE ANEXO 2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'c_instancia' => '027',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3309',
                'c_ubigeo' => '070106',
                'x_corto' => '2JF',
                'x_nom_instancia' => '2° JUZGADO DE FAMILIA - SEDE JUZG. FAMILIA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'c_instancia' => '028',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3309',
                'c_ubigeo' => '070106',
                'x_corto' => 'JFT',
                'x_nom_instancia' => 'JUZGADO DE FAMILIA TRANSITORIO - SEDE JUZG. FAMILIA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'c_instancia' => '029',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPLT',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO TRANSITORIO - SEDE PACHACUTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'c_instancia' => '030',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3306',
                'c_ubigeo' => '070106',
                'x_corto' => '1JP',
            'x_nom_instancia' => '1° JUZGADO PENAL UNIPERSONAL (AD. FUNC. ESTANDAR) -SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'c_instancia' => '031',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '2JP',
            'x_nom_instancia' => '2° JUZGADO PENAL UNIPERSONAL (AD. FUNC. ESTANDAR) -SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'c_instancia' => '032',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3306',
                'c_ubigeo' => '070106',
                'x_corto' => '1JPE',
            'x_nom_instancia' => '1° JUZGADO INV. PREP. (AD. FUNC. ESTANDAR) -SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'c_instancia' => '033',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '2JPE',
            'x_nom_instancia' => '2° JUZGADO INV. PREP. (AD. FUNC. ESTANDAR) -SEDE NCPP',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'c_instancia' => '034',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '3JUP',
            'x_nom_instancia' => '3° JUZGADO PENAL UNIPERSONAL (AD. FUNCIONES) - SEDE CENTRAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'c_instancia' => '035',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3303',
                'c_ubigeo' => '070106',
                'x_corto' => '1SCT',
                'x_nom_instancia' => 'SALA CIVIL TRANSITORIA - SEDE ANEXO 2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'c_instancia' => '036',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3311',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPLL',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO LABORAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'c_instancia' => '037',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3311',
                'c_ubigeo' => '070106',
                'x_corto' => 'JT',
                'x_nom_instancia' => 'JUZGADO DE TRABAJO',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'c_instancia' => '038',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3311',
                'c_ubigeo' => '070106',
                'x_corto' => 'SL',
                'x_nom_instancia' => 'SALA LABORAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'c_instancia' => '039',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '3JIP',
                'x_nom_instancia' => '3° JUZGADO DE INVESTIGACION PREPARATORIA - PROC. FLAGRANCIA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'c_instancia' => '040',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => '1JIP',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACION PREPARATORIA - MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'c_instancia' => '041',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3313',
                'c_ubigeo' => '070106',
                'x_corto' => '2SPA',
                'x_nom_instancia' => '2° SALA PENAL DE APELACIONES - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'c_instancia' => '042',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '3JUP',
                'x_nom_instancia' => '3° JUZGADO PENAL UNIPERSONAL - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'c_instancia' => '043',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '4JUP',
                'x_nom_instancia' => '4° JUZGADO PENAL UNIPERSONAL - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'c_instancia' => '044',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '4JUP',
                'x_nom_instancia' => '4° JUZGADO PENAL UNIPERSONAL - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'c_instancia' => '045',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => '4JIP',
                'x_nom_instancia' => '4° JUZGADO DE INVESTIGACION PREPARATORIA - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'c_instancia' => '046',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => '1JIP',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACION PREPARATORIA - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'c_instancia' => '047',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JP',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUNC. 4 JIP) - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'c_instancia' => '048',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JP',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUN. 3 JUP) - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'c_instancia' => '049',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JP',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUNC. 4 JUP) - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'c_instancia' => '050',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3308',
                'c_ubigeo' => '070107',
                'x_corto' => 'JP',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUNC. JIP) - SEDE MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'c_instancia' => '051',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => 'JP',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUNC. JIP) - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'c_instancia' => '052',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '1JP',
                'x_nom_instancia' => '1° JUZGADO PENAL LIQUIDADOR - SEDE VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'c_instancia' => '053',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '2JP',
                'x_nom_instancia' => '2° JUZGADO PENAL LIQUIDADOR - SEDE CENTRAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'c_instancia' => '054',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '1JPT',
                'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR TRANSITORIO - SEDE CENTRAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'c_instancia' => '055',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3313',
                'c_ubigeo' => '070106',
                'x_corto' => '1SPL',
            'x_nom_instancia' => '1° SALA PENAL LIQUIDADORA (AD. FUNC. 1° SPA) - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'c_instancia' => '056',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3313',
                'c_ubigeo' => '070106',
                'x_corto' => '2SPL',
            'x_nom_instancia' => '2° SALA PENAL LIQUIDADORA (AD. FUNC. 2° SPA) - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'c_instancia' => '057',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3313',
                'c_ubigeo' => '070106',
                'x_corto' => '1SPA',
                'x_nom_instancia' => '1° SALA PENAL DE APELACIONES - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'c_instancia' => '058',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => '1JCT',
                'x_nom_instancia' => 'JUZGADO CIVIL TRANSITORIO - SEDE PACHACUTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'c_instancia' => '059',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3308',
                'c_ubigeo' => '070107',
                'x_corto' => '1JCT',
                'x_nom_instancia' => 'JUZGADO CIVIL TRANSITORIO - SEDE MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'c_instancia' => '060',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => '1JCT',
                'x_nom_instancia' => 'JUZGADO CIVIL TRANSITORIO - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'c_instancia' => '061',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => 'JC',
                'x_nom_instancia' => 'JUZGADO CIVIL - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'c_instancia' => '062',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => 'JC',
                'x_nom_instancia' => 'JUZGADO CIVIL - SEDE MI PERÚ',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'c_instancia' => '063',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => 'JPL',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO - SEDE MI PERÚ',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'c_instancia' => '064',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPL',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO - SEDE PACHACÚTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'c_instancia' => '065',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => 'JC',
                'x_nom_instancia' => 'JUZGADO CIVIL - SEDE PACHACÚTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'c_instancia' => '066',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => '1JPT',
                'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR TRANSITORIO - SEDE MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'c_instancia' => '067',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACION PREPARATORIA TRANSITORIO',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'c_instancia' => '068',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JCT',
                'x_nom_instancia' => 'JUZGADO PENAL COLEGIADO TRANSITORIO',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'c_instancia' => '069',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGAC PREP TRANSITORIO - SEDE PACHACUTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'c_instancia' => '070',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => 'JUT',
                'x_nom_instancia' => 'JUZGADO PENAL UNIPERSONAL TRANSITORIO -SEDE JUDICIAL MI PERU',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'c_instancia' => '071',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGAC PREPARATORIA TRANSITORIO - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'c_instancia' => '072',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => 'JUT',
                'x_nom_instancia' => 'JUZGADO PENAL UNIPERSONAL TRANSITORIO - SEDE ANCON',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'c_instancia' => '073',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3302',
                'c_ubigeo' => '070106',
                'x_corto' => '1SC',
                'x_nom_instancia' => 'SALA CIVIL - SEDE CENTRAL',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'c_instancia' => '988',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3398',
                'c_ubigeo' => '070106',
                'x_corto' => '1SM',
                'x_nom_instancia' => 'SALA MIXTA TRANSITORIA DE VENTANILLA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'c_instancia' => '989',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3397',
                'c_ubigeo' => '070106',
                'x_corto' => '1JIP',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACION PREPARATORIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'c_instancia' => '990',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3398',
                'c_ubigeo' => '070106',
                'x_corto' => '1SM',
                'x_nom_instancia' => 'SALA MIXTA - VENTANILLA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'c_instancia' => '991',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '04',
                'c_sede' => '3397',
                'c_ubigeo' => '070106',
                'x_corto' => '1JMT',
                'x_nom_instancia' => 'JUZGADO MIXTO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'c_instancia' => '992',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3395',
                'c_ubigeo' => '070106',
                'x_corto' => '1JFT',
                'x_nom_instancia' => 'JUZGADO DE FAMILIA TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'c_instancia' => '993',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3397',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPT',
                'x_nom_instancia' => 'JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'c_instancia' => '994',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3397',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPLT',
                'x_nom_instancia' => 'JUZGADO DE PAZ LETRADO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'c_instancia' => '995',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3396',
                'c_ubigeo' => '070106',
                'x_corto' => '2JPL',
                'x_nom_instancia' => '2° JUZGADO DE PAZ LETRADO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'c_instancia' => '996',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '04',
                'c_sede' => '3399',
                'c_ubigeo' => '070106',
                'x_corto' => '3JM',
                'x_nom_instancia' => 'JUZGADO MIXTO DE VENTANILLA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'c_instancia' => '997',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3399',
                'c_ubigeo' => '070106',
                'x_corto' => '2JM',
                'x_nom_instancia' => '2° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'c_instancia' => '998',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3399',
                'c_ubigeo' => '070106',
                'x_corto' => '1JM',
                'x_nom_instancia' => '1° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'c_instancia' => '999',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '05',
                'c_sede' => '3399',
                'c_ubigeo' => '070106',
                'x_corto' => '1JPL',
                'x_nom_instancia' => '1° JUZGADO DE PAZ LETRADO-VENTANILLA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'c_instancia' => '895',
                'c_distrito' => '33',
                'c_provincia' => '95',
                'c_org_jurisd' => '05',
                'c_sede' => '3382',
                'c_ubigeo' => '150112',
                'x_corto' => '9JPL',
                'x_nom_instancia' => '9° JPL - Sede JPL San Martín - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'c_instancia' => '896',
                'c_distrito' => '33',
                'c_provincia' => '96',
                'c_org_jurisd' => '05',
                'c_sede' => '3383',
                'c_ubigeo' => '150106',
                'x_corto' => '1JPL',
                'x_nom_instancia' => '1° JPL Sede MBJ Carabayllo - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'c_instancia' => '897',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '04',
                'c_sede' => '3385',
                'c_ubigeo' => '150135',
                'x_corto' => '1JMT',
                'x_nom_instancia' => '1x1a JUZGADO MIXTO TRANSITORIO-Sede Sao Paolo - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'c_instancia' => '898',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '05',
                'c_sede' => '3384',
                'c_ubigeo' => '150135',
                'x_corto' => '4JPL',
                'x_nom_instancia' => '4° JPL Familia-Civil-Laboral Condevilla - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'c_instancia' => '899',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '04',
                'c_sede' => '3385',
                'c_ubigeo' => '150135',
                'x_corto' => '3JM',
                'x_nom_instancia' => '3° JUZGADO MIXTO - Sede MBJ Condevilla - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'c_instancia' => '900',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '03',
                'c_sede' => '3385',
                'c_ubigeo' => '150135',
                'x_corto' => '2JPE',
                'x_nom_instancia' => '2° JUZGADO PENAL - Sede MBJ Condevilla - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'c_instancia' => '901',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '03',
                'c_sede' => '3386',
                'c_ubigeo' => '150135',
                'x_corto' => '1JPE',
                'x_nom_instancia' => '1° JUZGADO PENAL - Sede MBJ Condevilla - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'c_instancia' => '902',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '04',
                'c_sede' => '3386',
                'c_ubigeo' => '150135',
                'x_corto' => '1JMI',
                'x_nom_instancia' => '2° JUZGADO MIXTO - Sede MBJ Condevilla - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'c_instancia' => '903',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '05',
                'c_sede' => '3386',
                'c_ubigeo' => '150135',
                'x_corto' => '1JPL',
            'x_nom_instancia' => '1° JPL FAMILIA (Condevilla) - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'c_instancia' => '904',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '04',
                'c_sede' => '3386',
                'c_ubigeo' => '150135',
                'x_corto' => '1JMI',
            'x_nom_instancia' => '1° JUZGADO MIXTO - (Condevilla) - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'c_instancia' => '905',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '05',
                'c_sede' => '3386',
                'c_ubigeo' => '150135',
                'x_corto' => '3JPL',
            'x_nom_instancia' => '3° JPL Penal (Condevilla) - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'c_instancia' => '906',
                'c_distrito' => '33',
                'c_provincia' => '97',
                'c_org_jurisd' => '05',
                'c_sede' => '3386',
                'c_ubigeo' => '150135',
                'x_corto' => '2JPL',
            'x_nom_instancia' => '2° JPL FAMILIA (Condevilla) - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'c_instancia' => '907',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '04',
                'c_sede' => '3388',
                'c_ubigeo' => '150125',
                'x_corto' => '1JM',
                'x_nom_instancia' => 'JUZGADO MIXTO TRANSITORIO DE PUENTE PIEDRA - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'c_instancia' => '908',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '03',
                'c_sede' => '3387',
                'c_ubigeo' => '150125',
                'x_corto' => '2JPT',
                'x_nom_instancia' => '2° JUZGADO PENAL TRANSITORIO - Pte Piedra - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'c_instancia' => '909',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '03',
                'c_sede' => '3387',
                'c_ubigeo' => '150125',
                'x_corto' => '1JPT',
                'x_nom_instancia' => '1° JUZGADO PENAL TRANSITORIO - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'c_instancia' => '910',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '04',
                'c_sede' => '3388',
                'c_ubigeo' => '150125',
                'x_corto' => '1JMI',
            'x_nom_instancia' => 'JUZGADO MIXTO - Pte Piedra (Av. Bs Aires) - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'c_instancia' => '911',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '05',
                'c_sede' => '3389',
                'c_ubigeo' => '150125',
                'x_corto' => '2JPL',
                'x_nom_instancia' => '2° JPL - Sede JPL Puente Piedra - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'c_instancia' => '912',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '05',
                'c_sede' => '3389',
                'c_ubigeo' => '150125',
                'x_corto' => '1JPL',
                'x_nom_instancia' => '1° JPL - Sede JPL Puente Piedra - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'c_instancia' => '913',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '03',
                'c_sede' => '3387',
                'c_ubigeo' => '150125',
                'x_corto' => '1JP',
                'x_nom_instancia' => '1° JUZGADO PENAL - PUENTE PIEDRA - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'c_instancia' => '914',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '03',
                'c_sede' => '3388',
                'c_ubigeo' => '150125',
                'x_corto' => '1JC',
                'x_nom_instancia' => 'JUZGADO CIVIL - PUENTE PIEDRA - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'c_instancia' => '915',
                'c_distrito' => '33',
                'c_provincia' => '98',
                'c_org_jurisd' => '05',
                'c_sede' => '3389',
                'c_ubigeo' => '150125',
                'x_corto' => '3JPL',
                'x_nom_instancia' => '3° JPL - Sede JPL Puente Piedra - CSJ Lima Norte',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'c_instancia' => '916',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '3JPU',
                'x_nom_instancia' => '3° JUZGADO PENAL UNIPERSONAL - Sede La Marina - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'c_instancia' => '917',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '2JPU',
                'x_nom_instancia' => '2° JUZGADO PENAL UNIPERSONAL - Sede La Marina - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'c_instancia' => '918',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '1JPU',
                'x_nom_instancia' => '1° JUZGADO PENAL UNIPERSONAL - Sede La Marina - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'c_instancia' => '919',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '1SPA',
                'x_nom_instancia' => 'SALA PENAL DE APELACIONES - Sede La Marina - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'c_instancia' => '920',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '1JIP',
                'x_nom_instancia' => 'JUZGADO INVESTIGACION PREPARATORIA - La Marina - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'c_instancia' => '921',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070104',
                'x_corto' => '5JPT',
                'x_nom_instancia' => '5TO. JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'c_instancia' => '922',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070104',
                'x_corto' => '4JPT',
                'x_nom_instancia' => '4TO. JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'c_instancia' => '923',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '3JPT',
                'x_nom_instancia' => '3° JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'c_instancia' => '924',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '2JPT',
                'x_nom_instancia' => '2° JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'c_instancia' => '925',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '1JPT',
                'x_nom_instancia' => '1ER. JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'c_instancia' => '926',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070104',
                'x_corto' => '1JPT',
                'x_nom_instancia' => 'J. ESP. PENAL TRANSIT-REOS EN CARCEL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'c_instancia' => '927',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '13JP',
                'x_nom_instancia' => 'JUZGADO PENAL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'c_instancia' => '928',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '12JP',
                'x_nom_instancia' => '12° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'c_instancia' => '929',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '11JP',
                'x_nom_instancia' => '11° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'c_instancia' => '930',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '10JP',
                'x_nom_instancia' => '10° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'c_instancia' => '931',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '9JP',
                'x_nom_instancia' => '9° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'c_instancia' => '932',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '8JP',
                'x_nom_instancia' => '8° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'c_instancia' => '933',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '7JP',
                'x_nom_instancia' => '7° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'c_instancia' => '934',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '6JP',
                'x_nom_instancia' => '6° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'c_instancia' => '935',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '5JP',
                'x_nom_instancia' => '5° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'c_instancia' => '936',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '4JP',
                'x_nom_instancia' => '4° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'c_instancia' => '937',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '3JP',
                'x_nom_instancia' => '3° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'c_instancia' => '938',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2JP',
                'x_nom_instancia' => '2° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'c_instancia' => '939',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1JP',
                'x_nom_instancia' => '1° JUZGADO PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'c_instancia' => '940',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '4JT',
                'x_nom_instancia' => '4°JUZG. DE TRABAJO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'c_instancia' => '941',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '3JT',
                'x_nom_instancia' => '3°JUZG. DE TRABAJO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'c_instancia' => '942',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2JT',
                'x_nom_instancia' => '2°JUZG. DE TRABAJO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'c_instancia' => '943',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1JT',
                'x_nom_instancia' => '1°JUZG. DE TRABAJO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'c_instancia' => '944',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '1JM',
                'x_nom_instancia' => '2° JUZGADO DE TRABAJO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'c_instancia' => '945',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '6JL',
                'x_nom_instancia' => 'J. ESPECIALIZADO DE TRABAJO TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'c_instancia' => '946',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '5JL',
                'x_nom_instancia' => '5° JUZGADO ESPECIALIZADO DE TRABAJO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'c_instancia' => '947',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '4JL',
                'x_nom_instancia' => '4° JUZGADO ESPECIALIZADO DE TRABAJO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'c_instancia' => '948',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '3JL',
                'x_nom_instancia' => '3° JUZGADO LABORAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'c_instancia' => '949',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2JL',
                'x_nom_instancia' => '2° JUZGADO LABORAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'c_instancia' => '950',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1JL',
                'x_nom_instancia' => '1° JUZGADO LABORAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'c_instancia' => '951',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '7JFT',
                'x_nom_instancia' => 'JUZGADO E. FAMILIA-TUTELAR INFRACTOR-TRANSIT. - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'c_instancia' => '952',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070104',
                'x_corto' => '6JFC',
                'x_nom_instancia' => 'JUZGADO E. FAMILIA-CIVIL TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'c_instancia' => '953',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3392',
                'c_ubigeo' => '070101',
                'x_corto' => '5JF',
                'x_nom_instancia' => '5° JUZGADO FAMILIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'c_instancia' => '954',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '4JF',
                'x_nom_instancia' => '4° JUZGADO FAMILIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'c_instancia' => '955',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '3JF',
                'x_nom_instancia' => '3° JUZGADO FAMILIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'c_instancia' => '956',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2JF',
                'x_nom_instancia' => '2° JUZGADO FAMILIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'c_instancia' => '957',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1JF',
                'x_nom_instancia' => '1° JUZGADO FAMILIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'c_instancia' => '958',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => 'JCT',
                'x_nom_instancia' => '2° JUZ. CONT. ADM. TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'c_instancia' => '959',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => 'JCAT',
                'x_nom_instancia' => '1° JUZ. CONT. ADM. TRANSITORIO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'c_instancia' => '960',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '6JC',
                'x_nom_instancia' => '6° JUZGADO CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'c_instancia' => '961',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '5JC',
                'x_nom_instancia' => '5° JUZGADO CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'c_instancia' => '962',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '4JC',
                'x_nom_instancia' => '4° JUZGADO CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'c_instancia' => '963',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '3JC',
                'x_nom_instancia' => '3° JUZGADO CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'c_instancia' => '964',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2JC',
                'x_nom_instancia' => '2° JUZGADO CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'c_instancia' => '965',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1JC',
                'x_nom_instancia' => '1° JUZGADO CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'c_instancia' => '966',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1ST',
                'x_nom_instancia' => 'SALA LABORAL TRANSITORIA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'c_instancia' => '967',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3391',
                'c_ubigeo' => '070101',
                'x_corto' => '1SL',
                'x_nom_instancia' => 'SALA ESPECIALIZADA LABORAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'c_instancia' => '968',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '4SP',
                'x_nom_instancia' => '4° SALA PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'c_instancia' => '969',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '3SP',
                'x_nom_instancia' => '3° SALA PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'c_instancia' => '970',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2SP',
                'x_nom_instancia' => '2° SALA PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'c_instancia' => '971',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1SP',
                'x_nom_instancia' => '1° SALA PENAL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'c_instancia' => '972',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2SM',
                'x_nom_instancia' => 'SALA MIXTA TRANSITORIA DEL CALLAO - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'c_instancia' => '973',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '2SC',
                'x_nom_instancia' => '2° SALA CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'c_instancia' => '974',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1SC',
                'x_nom_instancia' => '1° SALA CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'c_instancia' => '975',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '3JPT',
                'x_nom_instancia' => '3° JUZGADO PENAL TRANSITORIO REOS LIBRES - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'c_instancia' => '976',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '2JPT',
                'x_nom_instancia' => '2° JUZGADO PENAL TRANSITORIO REOS LIBRES - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'c_instancia' => '977',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '1JPT',
                'x_nom_instancia' => '1° JUZGADO PENAL TRANSITORIO REOS LIBRES - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'c_instancia' => '978',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '02',
                'c_sede' => '3394',
                'c_ubigeo' => '070101',
                'x_corto' => '1SC',
                'x_nom_instancia' => 'SALA CIVIL - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'c_instancia' => '979',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '5JPT',
                'x_nom_instancia' => '5° JUZGADO PENAL TRANSITORIO - SEDE LA MARINA - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'c_instancia' => '980',
                'c_distrito' => '33',
                'c_provincia' => '99',
                'c_org_jurisd' => '03',
                'c_sede' => '3393',
                'c_ubigeo' => '070101',
                'x_corto' => '4JPT',
                'x_nom_instancia' => '4° JUZGADO PENAL TRANSITORIO REOS LIBRES - CSJ Callao',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'c_instancia' => '074',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => 'JPU',
                'x_nom_instancia' => 'JUZGADO PENAL UNIPERSONAL-ANCÓN Y SANTA ROSA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'c_instancia' => '075',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => 'JPU',
                'x_nom_instancia' => 'JUZGADO PENAL UNIPERSONAL-MI PERÚ',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'c_instancia' => '076',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => 'JIP',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACIÓN PREPARATORIA-PACHACÚTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'c_instancia' => '077',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACIÓN PREPARATORIA TRANS. - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'c_instancia' => '078',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPUT',
                'x_nom_instancia' => 'JUZGADO PENAL UNIPERSONAL TRANSITORIO - VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'c_instancia' => '079',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3314',
                'c_ubigeo' => '070107',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACIÓN PREPARATORIA TRANSITORIO - MI PERÚ',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'c_instancia' => '080',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACIÓN PREPARATORIA TRANSITORIO-PACHACÚTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'c_instancia' => '081',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => '2JUT',
                'x_nom_instancia' => '2° JUZGADO PENAL UNIPERSONAL TRANSITORIO - PACHACÚTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'c_instancia' => '082',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3310',
                'c_ubigeo' => '070106',
                'x_corto' => '1JUT',
                'x_nom_instancia' => '1° JUZGADO PENAL UNIPERSONAL TRANSITORIO - PACHACÚTEC',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'c_instancia' => '083',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3307',
                'c_ubigeo' => '150102',
                'x_corto' => 'JIPT',
                'x_nom_instancia' => 'JUZGADO DE INVESTIGACIÓN PREP. TRANS.-SANTA ROSA Y ANCÓN',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'c_instancia' => '084',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPLT',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUNC. JIPT)-VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'c_instancia' => '085',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3312',
                'c_ubigeo' => '070106',
                'x_corto' => 'JPLT',
            'x_nom_instancia' => 'JUZGADO PENAL LIQUIDADOR (AD. FUNC. JPUT)-VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'c_instancia' => '086',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '03',
                'c_sede' => '3301',
                'c_ubigeo' => '070106',
                'x_corto' => '1JPC',
                'x_nom_instancia' => 'JUZGADO PENAL COLEGIADO - SEDE VENTANILLA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'c_instancia' => '087',
                'c_distrito' => '33',
                'c_provincia' => '01',
                'c_org_jurisd' => '02',
                'c_sede' => '3313',
                'c_ubigeo' => '070106',
                'x_corto' => 'SPAT',
                'x_nom_instancia' => 'SALA PENAL DE APELACIONES TRANSITORIA - SEDE PRESIDENCIA',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}